# Generated by Django 4.2.4 on 2023-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_aposentados_tipo_beneficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposentados',
            name='mci',
            field=models.CharField(max_length=20),
        ),
    ]
