# Generated by Django 4.2.4 on 2023-08-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_aposentados_mci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposentados',
            name='idade',
            field=models.CharField(max_length=10),
        ),
    ]
