# Generated by Django 4.2.4 on 2023-08-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_aposentados_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposentados',
            name='alfabetizado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aposentados',
            name='dia_recebimento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aposentados',
            name='limite_vigente',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aposentados',
            name='precisa_prova_vida',
            field=models.CharField(max_length=10),
        ),
    ]
