# Generated by Django 4.2.4 on 2023-08-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_aposentados_alfabetizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposentados',
            name='agencia',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
