# Generated by Django 4.2.4 on 2023-08-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
        migrations.AlterField(
            model_name='aposentados',
            name='agencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aposentados',
            name='alfabetizado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aposentados',
            name='conta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aposentados',
            name='idade',
            field=models.CharField(max_length=255),
        ),
    ]
