# Generated by Django 4.2.4 on 2023-08-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_delete_upload_alter_aposentados_agencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposentados',
            old_name='alfabetizado',
            new_name='analfabetizado',
        ),
        migrations.AlterField(
            model_name='aposentados',
            name='ultimo_atendimento',
            field=models.DateField(auto_now=True),
        ),
    ]
