# Generated by Django 4.2.4 on 2023-08-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_rename_alfabetizado_aposentados_analfabetizado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposentados',
            old_name='analfabetizado',
            new_name='analfabeto',
        ),
    ]
